# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # Database Service (Mysql)
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    restart: always
    container_name: mini-db
    environment:
      MYSQL_DATABASE: university
      MYSQL_USER: miniproject1
      MYSQL_PASSWORD: minipassword
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "root", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: ./ # Use an image built from the specified dockerfile in the directory.
      dockerfile: Dockerfile
    container_name: app-server-1
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - db:
          condition: service_healthy
    environment:
      # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mini-db:3306/university?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: miniproject1
      SPRING_DATASOURCE_PASSWORD: minipassword
    networks:
      # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
# Volumes
volumes:
  db-data: # Networks to be created to facilitate communication between containers
networks:
  backend:
